### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jayvdb** [NarrativeTeam/geogotchi#1]
Python 3 support would be good.  Here is one error I found.

``` python
>>> gg.search(q="Kabupaten Seram Bagian Barat")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/geogotchi/base.py", line 236, in search
    params[query_name] = conv(kwarg_val)
  File "/usr/lib/python3.4/site-packages/geogotchi/base.py", line 47, in _make_utf8
    if isinstance(s, unicode):
NameError: name 'unicode' is not defined
```

**Comment by ghost** [comment]
See #2 :)
